server:
  port: 8087

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  cloud:
    stream:
      bindings:
        publishProductState-out-0:
          destination: product.state
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: true
      minimumIdle: 3
      maximumPoolSize: 10
      poolName: price-orders-main-pool
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/price_orders
    username: postgres
    password: Pass999T
  liquibase:
    change-log: classpath:/db/liquibase/changelog-master.xml
    enabled: true

app:
  inner:
    migration:
      pageSize: 100
  searchSelect:
    defaultLimit: 50
integration:
  source: price-orders
  trace:
    generator:
      prefix: price-orders-
      maxLength: 6

telegram:
  bot-token: 8519193034:AAEZmmc3zQ_GH5FNPRkMefS-8BJF40_soTA
